from enum import Enum


class EducationTypeEnum(str, Enum):
    DOTTORATO = "DOTTORATO"
    LAUREA_CICLO_UNICO = "LAUREA_CICLO_UNICO"
    LAUREA_MAGISTRALE = "LAUREA_MAGISTRALE"
    LAUREA_TRIENNALE = "LAUREA_TRIENNALE"
    LAUREA_VECCHIO_ORDINAMENTO = "LAUREA_VECCHIO_ORDINAMENTO"
    MASTER_ALTRI = "MASTER_ALTRI"
    MASTER_II_LIV = "MASTER_II_LIV"
    MASTER_I_LIV = "MASTER_I_LIV"
    SCUOLA_SUPERIORE = "SCUOLA_SUPERIORE"
    TERZA_MEDIA = "TERZA_MEDIA"

    def __str__(self) -> str:
        return str(self.value)
